# This is optimized version for local development
FROM node:14.17-alpine
LABEL maintainer="Roman Podlinov"

# Update OS
RUN apk --no-cache add ca-certificates && update-ca-certificates

EXPOSE 3000
CMD ["node", "src/index.js"]

# Create the working dir
RUN mkdir -p /opt/app && mkdir /opt/.cache

# Set the working dir
WORKDIR /opt/app


