FROM node:12-alpine
LABEL maintainer="Roman Podlinov"

# Update OS
RUN apk --no-cache add ca-certificates && update-ca-certificates

EXPOSE 3000
CMD ["node", "src/index.js"]

# Create the working dir
RUN mkdir -p /opt/app && mkdir /opt/.cache
WORKDIR /opt/app

# Install packages + Prepare cache file
#RUN yarn config set cache-folder /opt/.cache \
#  && yarn
#  && cd /opt/app && ln -s /cache/node_modules node_modules \
#  && tar czf /.yarn-cache.tgz /usr/local/share/.cache/yarn

COPY . .
