# This is dockerfile version for local development;
# it's optimized for fast start locally
FROM node:14.17-alpine

# you need to use docker-compose.yml to enable debug support
ARG DEBUG_PORT_NAME
EXPOSE 3000 $DEBUG_PORT_NAME


# Update OS & certificates
RUN apk update && \
    apk upgrade && \
    apk --no-cache add ca-certificates  && \
    update-ca-certificates && \
    rm -fR /var/cache/apk/*

# Create a cache folder for yarn and set it
RUN mkdir -p /opt/yarn-cache && yarn config set cache-folder /opt/yarn-cache

# Create the working dir
RUN mkdir -p /opt/app

# Set the working dir
WORKDIR /opt/app

